- python/Tip Calculator.py
This is a Tip Calculator Project in Python to calculate the tip, Hope you like it..
> Create Tip Calculator.py

- python/BMI Calculator.py
Added a new Python project namely BMI calculator.py Hope you like it 🙂
> Create BMI Calculator.py

- C++/Pattern Printing Problems/PyramidPattern_asterisk.cpp
- README.md
C++ Program to print pyramid pattern of asterisks.
> Pattern Printing Problem in C++

- python/number guesser.py
A random number from 1 to 10 is generated and the player has to guess it.
The program also keeps track of number of tries by the player, reporting it at the end of the game.
> I added a number guessing game in python

- java/oddevenchecker.java
This java code returns the user input number whether it is odd or even.
> Created oddeven checker using java

- python/oddevenchecker.py
This python code will check the odd or even number from the input of the user
> Created oddevenchecker.py

- C++/oddevenchecker.cpp
This cpp code returns the user input as odd or even.
> Created odd even checker in C++

- python/checkleapyear.py
This code uses calendar library to get the leap year.
> Created leap year checker

- python/Hand Cricket.py
- 🏏 Hand Cricket
- ✨ Basic Game
- 🌐 Python
- 🚩 Very useful and helpful for the beginner
This PR includes the addition of the basic program of the Hand Cricket Game with simple conditional and logical statements.
[<img src="https://img.shields.io/badge/GitHub-IncrediblePro-blue?logo=github&style=for-the-badge" alt="IncrediblePro">](https://github.com/IncrediblePro)
> Create Hand Cricket.py

- java/bubble-sort.java
Issue: none
Changes propsosed: added bubble sort java program
Errors: none
Mentions:
> added bubble sort

- java/StringReverse.java
The Program reverses a string in Java Language.
Issue: NA. As part of the hactoberfest 2022.
Changes proposed: The commit adds a new file StringReverse.java to the /java folder. The code in the file aims at reversing a string and outputting it .
Errors: No errors. The program runs successfully.
Thanks.
> Java program to reverse a string

- java/intersection2arr.java
please add a hacktobrfest-accepted lable after merger
> add a program intersection2array in  java

- java/TriplyLinkedList.java
Issue: None
Changes propsosed: Added TriplyLinkedList.java file
Errors: None
Mentions:
> Create TriplyLinkedList.java file

- golang/PhoneNumberCheck.go
simple checker number
writte in go
how to run?
go run PhoneNumberChecker.go <number>
> add checker number

- java/isuruvithanage.java
Issue: There is no validation in user input
Changes proposed: Validate the user input whether the array length input is an integer value or double value.
Errors: InputMismatchException
Mentions: I added validation for input so the user will only input an integer value for array length and I changed the array type to double so the users can sort double values also.
> In Bubble sorting JAVA program added some validations

- C++/sorting/MergeSort.cpp
Issue: ~
Changes proposed: Added Merge Sort Algorithm
Errors: None
Mentions: ~
> Created MergeSort.cpp

- python/What day is today.py
Tells what day is today
Issue: 
Errors: 
Mentions:
> Create What day is today.py

- C++/sorting/bubbleSort.cpp
Adding a bubble sort example as contribution. #hacktoberfest2022
Issue: 
Errors: 
Mentions:
> Add BubbleSort

- timSort.java
> timSort.java

- python/Coffee-Palace.py
A simple coffee palace program applying the topic of OOP
Issue: 
Errors: 
Mentions:
> Add coffee palace program

- python/Modern CLI Calculator
I created and updated my Modern CLI Calculator, Hope you like it,, 🙂
> Update Modern CLI Calculator

- C++/To_find_keywords.c
- C++/To_find_keywords.txt
Hey!! I want to you to please add these files in your repository as it contains the concept of file handling concept in C language.
Thank you.
> C program to find the number of keywords in a given Text file !!

- java/LRUCache.java
Optimal solution for important interview problem Least Recently Used Cache. This solution is written in Java.
Time Complexity of get() : O(1)
Time Complexity of put() : O(1)
Issue: 
Errors: 
Mentions:
> Create LRUCache.java for HacktoberFest-2022

- java/MaxSubArray.java
Issue: NA
Changes proposed: Add Maximum Subarray solution in java folder
Errors: NA
Mentions: Solution in java using Kadane's Algorithm
> Maximum Subarray Solution

- C++/rotateimage.cpp
Issue:  NA
Changes propsosed: Add rotate image problem solution 
Errors: NA
Mentions: It is CPP file which is added in c++ folder.
> rotate image problem solution

- java/PasswordValidation.java
Issue: 
Password Validator
Changes proposed: 
Add a program to validate password
Errors: 
-
Mentions: 
-
> Add password validator

- java/tictactoe.java
> Added Tic Tac Toe Game

- C++/uncommonCharacter.cpp
Issue: Find uncommon characters of the two strings in c++
Changes proposed: Added c++ file
Errors: none
Mentions:
@InvisiblePro
> added uncommon character program solution in c++

- C/Polynomial Addition.c
> polynomial addition

- C/merge sort.c
> Added merge sort using C language

- java/MergeSort.java
> Merge Sort Using Java

- SECURITY.md
- scala/HelloWorld.scala
Issue:  None
Changes propsosed:  Added scala 
Errors: 0
Mentions:
> Added Scala Hello World

- C++/bucketsort.cpp
- C++/karatsuba.cpp
- C++/randomised_quicksort.cpp
Added Bucket sort, Karatsuba Algorithm and Randomised Quicksort program to C++
Please merge it 
thanks and regards.
> added 3 algorithms to c++ folder

- C++/Binary Search Problems/Aggressive_cows.cpp
Issue: 
In C++ folder no binary search problem was present. Even a folder did not exist.
Changes proposed: 
Added a Binary search folder and solution with the approach of Aggressive cows using CPP.
Errors: 
NA
Mentions: 
@InvisiblePro
> Added binary search problem 

- golang/TowerOfHanoi.go
> add Tower of Hanoi Algorithm in Golang

- python/fibonacci.py
> Added Fibonacci in Python

- JavaScript/TicTacToeGame/index.html
- JavaScript/TicTacToeGame/script.js
- JavaScript/TicTacToeGame/style.css
Issue: To build the Tic Tac Toe game using JavaScript
Changes proposed: Game project
Errors: 0
Mentions: @InvisiblePro
> add game project files

- C++/maximum_points_on_same_line.cpp
> Count maximum number of points on same line

- python/FillMissingDataInArray.py
Issue:  A NumPy program to find the missing data in a given array and fill it with zeros
Changes propsosed: Added FillMissingDataInArray.py file in python folder.
Errors:  N/A
> A NumPy program to find the missing data in a given array and fill it with zeros

- Radix Sort.java
Issue: Radix sort
Errors: 
Mentions:
> Created radix sort implementation in java

- java/MaxInArray.java
Added a java solution to find out the maximum value in an array
> Added maximum value in array java solution

- java/quickSort.java
> Quick Sort in Java

- python/dragon_game.py
Issue: Added dragon game created using python.
Changes proposed: Created from scratch. No changes.
Errors: No errors.
Mentions: None.
Thank you for the opportunity.
> Add dragon game code

- java/CyclicSort.java
- java/SelectionSort.java
> added two files, selection sort and cyclic sort

- C/heap sort.c
Issue: Create heap sort.c
Changes propsosed: heap sort algorithm code
> Create heap sort.c

- python/(Message Coder and Decoder) Caesar Cipher.py
Issue:  #187
Changes propsosed: Added Message Coder and Decoder (Caesar Cipher)
Errors: No errors
Mentions: @InvisiblePro
> Added Message Coder and Decoder (Caesar Cipher)

- python/Snake_Game.py
> Snake_Game 

- Closest Palindrome
> Create Closest Palindrome

- magical number
> Create magical number

- java/Solution.java
> Create Solution.java(n -Queens)

- C++/InsertionSort.cpp
Issue: Adding types of Sorting Algorithmn
Changes propsosed: Added Insertion Sort
Errors: NA
Mentions: NA
> Added the implementation of "Insertion Sort".

- C++/sorting/HeapSort.cpp
Issue: Adding all Sorting Algorithms
Changes proposed:  Added HeapSort cpp code
Errors: 
Mentions:
> created HeapSort.cpp

- C++/Longest Common Subsequence
> Longest Common Subsequence

- kadanes_algorithm.java
> kadanes algorithm.java

- java/towerOfHanoi.java
> added tower of hanoi

- python/Guess_the_number.py
Changes propsosed: Create Guess_the_number
Mentions:
> Create Guess_the_number.py has multiple levels

- java/Snake Game/GameFrame.java
- java/Snake Game/GamePanel.java
- java/Snake Game/README.md
- java/Snake Game/SnakeGamer.java
Issue: 
Changes proposed: Snake Game In Java Language with Different Features
Errors: 
Mentions:
> Snake Game In Java Language with Different Features

- java/WordLadder.java
Issue: N/A
Changes propsosed:
Add WordLadder.java
> add WordLadder

- Guess the number game in java
hactoberfest contributer 2022
Issue: 
Errors: 
Mentions:
> Guess the number in java

- java/TRANSPOSE_OF_MATRIX.java
> transpose_of_matrix java file

- C++/create_singly_linked_list.cpp
> Created implement Singly Linked List in Cpp

- C/sudoku.c
created sudoku using c
Issue: 
Errors: 
Mentions:
> created sudoku.c

- python/tic_tac_toe.py
created tic-tac-toe using python
Issue: 
Errors: 
Mentions:
> created tic-tac-toe

- python/password_generator.py
created the password generator using python
Issue: 
Errors: 
Mentions:
> created password generator

- java/reverse_sentence.java
created the program reverse sentence using java
Issue: 
Errors: 
Mentions:
> created reverse sentence.java

- java/GraphUsingAdjacencyMatrix.java
Issue:  updated with a new code
Changes propsosed: Implementation of graph using adjacency matrix code uploaded
Errors: NA
Mentions: hacktoberfest22
> Graph Using Adjacency Matrix

- python/Python Website Scrapper and Email Automation.py
Prerequisites-
- Libraries Required to be installed- 
- requests
- bs4
- smtplib
- email
This porgramme pulls our the Headlines from HackerNews webpage and sends a list of Headlines with their links through emails to others.
> Python WebPage Scrapper & Automated Email Delivery

- C++/sort-an-array-of-0s-1s-2s.cpp
> Added sort-an-array-of-0s-1s-2s

- C++/Search a 2D Matrix
> Create Search a 2D Matrix

- java/queue/ArrayQueue.java
- java/queue/LinkedQueue.java
- java/queue/Queue.java
- java/stack/ArrayStack.java
- java/stack/LinkedStack.java
- java/stack/RPN.java
- java/stack/Stack.java
> added queue and stack implementation in java

- python/hacktoberfest22-quiz.py
Issue: Created 2022 Hacktoberfest Quiz in Python
Changes propsosed: Requires testing
Errors: unkown
Mentions: N/A
> Hacktoberfest Quiz 2022

- python/word_location.py
> Added find word location in python

- C++/Play_music.cpp
> Added code in cpp to play a music file

- java/Remove_nth_node.java
leetcode question
Issue: 
Errors: 
Mentions:
> Remove_nth_node

- java/Doubly_Linked_List.java
- java/Singly_Linked_List.java
Programs added:
1. Singly Linked List
2. Doubly Linked List
Issue: 
N/A
Added Programs for Linked Lists in Java
Errors: 
Mentions:
> Added Linked List programs.

- java/TrapRainWater.java
> TrapRainWater.java

- JavaScript/Calculator/calci.css
- JavaScript/Calculator/calci.js
- JavaScript/Calculator/index.html
Issue: No issue
Changes propsosed:  Just added calculator
Errors: No Errors
Mentions: Thank You @IncrediblePro for making this repo.
> Added Calculator

- java/Kadane.java
> added Kadane's algorithm java code
